const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const root = path.resolve(__dirname, '..')
const design = fs.readFileSync(path.resolve(root, '..', '.design/Frontend/DESIGN_SYSTEM.md'), 'utf8')
const css = fs.readFileSync(path.join(root, 'src/App.css'), 'utf8')
const app = fs.readFileSync(path.join(root, 'src/App.tsx'), 'utf8')
test('design system contract exposes required tokens and responsive surface', () => {
  for (const token of ['#00d4a4', '#0a0a0a', '#e5e5e5']) assert.match(design, new RegExp(token.replace('#', '\\#')))
  assert.match(css, /border-radius:999px/)
  assert.match(css, /max-width:720px/)
  for (const state of ['loading', 'current', 'Indisponível']) assert.match(app, new RegExp(state))
})
